{{ if .Values.green.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-hello-world.fullname" . }}-green
  labels:
    app.kubernetes.io/name: {{ include "java-hello-world.name" . }}
    helm.sh/chart: {{ include "java-hello-world.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    slot: green
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "java-hello-world.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      slot: green
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "java-hello-world.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        slot: green
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageGreen.repository }}:{{ .Values.imageGreen.tag }}"
          imagePullPolicy: {{ .Values.imageGreen.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{ end }}