{{- if .Values.ingress.enabled -}}
{{- $fullName := include "java-hello-world.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "java-hello-world.name" . }}
    helm.sh/chart: {{ include "java-hello-world.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: java.p0pc0rn.cf
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}-blue
              servicePort: http
    - host: staging.p0pc0rn.cf
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ $fullName }}-green
              servicePort: http
{{- end }}
