apiVersion: v1
kind: Service
metadata:
  name: {{ include "java-hello-world.fullname" . }}-green
  labels:
    app.kubernetes.io/name: {{ include "java-hello-world.name" . }}
    helm.sh/chart: {{ include "java-hello-world.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "java-hello-world.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}